### ISSUE TITLE
Add 48bit MAC address in tag data

### ISSUE THREAD

**Issue by balda** [pakastin/node-ruuvitag#17]
The 48bit MAC address is broadcasted with data format 5 (see https://github.com/ruuvi/ruuvi-sensor-protocols/blob/master/dataformat_05.md).

Can it be added to tag data? It's usefull on macos where tag ID is not always the same.

**Comment by pakastin** [comment]
Added!

**Comment by balda** [comment]
Thanks! :)

**Comment by balda** [comment]
Could you please format MAC address with a fixed width as explained in https://github.com/balda/ruuvitag-discovery/issues/6 ?
Thanks :)

**Comment by pakastin** [comment]
Ah crap, I’ll fix it right away! 🤦‍♂️👍

**Comment by pakastin** [comment]
Fixed and released (patch)!
