### ISSUE TITLE
Having trouble with discovering Ruuvi Tags

### ISSUE THREAD

**Issue by robctsgps** [pakastin/node-ruuvitag#19]
Hey there. Just wanted say that I really like the app for simple BLE scanning. My issue is that when I run the program via ruuvi-iothub, the program quite often will never discover my tags and start reporting them into Azure IoT Hub. What I have found is that if place plastic between the battery and the tag power terminal, start the program on my rpi, then remove the plastic, the program will discover the ruuvi tag. My goal is for it to always find tags without having to power cycle them. Any insight would be great.

**Comment by DG12** [comment]
Some versions of the firmware include a "startup" phase during which the packets are transmitted much more frequently than in "normal" operating mode. 
Pressing the R button is better than power off/on.
