### ISSUE TITLE
Stops receiving data

### ISSUE THREAD

**Issue by jpalo** [pakastin/node-ruuvitag#28]
For the past week (started 05-05-2020), node-ruuvitag intermittently stops receiving data from the tags. It runs fine for minutes or hours, then nothing. I have logging on `updated` event handler, and it just stops getting called. There are no exceptions or errors detected and the node app is running.

```
    tag.on('updated', data => {
        log.info('Got data ', data);
```

Is there a way to dig out some noble related logs to find out what is going on in the background?

**Comment by jpalo** [comment]
Appears my Bluetooth version had updated to 5.50 `bluetoothctl - v`. Downgraded back to 5.43 and it has now been running fine for days.

**Comment by pakastin** [comment]
I’ve started to witness the same. Tried to fix it with stateChange now, let’s see if it helps..
