### ISSUE TITLE
Feature: add MAC address and Id to the data body

### ISSUE THREAD

**Issue by enbochen** [pakastin/node-ruuvitag#4]
Is that possible to add MAC address and id to the body of data? It might be quite useful to identify the message source. Thanks!

**Comment by Espesen** [comment]
You can access ruuviTag instance's id inside the closure. I updated the example in b25c5a2. I should dig into MAC address later when I have some spare time. Thanks for request!

**Comment by enbochen** [comment]
Thanks for the quick reply. Looking forward to having the new feature.

**Comment by Espesen** [comment]
It seems to me that in noble (dependency of node-ruuvitag) address and id are essentially same thing:
https://github.com/sandeepmistry/noble/blob/3920ceecd9dd437d2d9f2cd00a065a178b6ccc0e/lib/hci-socket/bindings.js#L169

**Comment by enbochen** [comment]
Nice, now we can have the id in our body. But I still hope we can get MAC address like [Scrin/RuuviCollector](https://github.com/Scrin/RuuviCollector/blob/master/src/main/java/fi/tkgwf/ruuvi/utils/RuuviUtils.java#L39). 
Do you think it's possible?
Thanks!

**Comment by enbochen** [comment]
An interesting finding:
There is the difference for id depending on OS because of using difference bluetooth utility library. For example:
Raspberry Pi: `e30fcc063c68` (MAC address)
Mac: `d0236c7f69a04b023ec25cb6889da002` (more like UUID)

**Comment by Espesen** [comment]
Thanks for pointing this out! I have tested the code only on Raspberry Pi.
