### ISSUE TITLE
EventEmitter memory leak 

### ISSUE THREAD

**Issue by enbochen** [pakastin/node-ruuvitag#5]
I have this problem when I use ruuvi.findTags() several times until it scans all of my beacons: 

`
(node:27535) Warning: Possible EventEmitter memory leak detected. 11 discover listeners added. Use emitter.setMaxListeners() to increase limit
`

Is there anyways to remove evenEmiiter when it re-scan?

**Comment by Espesen** [comment]
This is a design flaw and I should restructure the code to avoid adding too many event listeners to the ```noble``` instance. I'll look into it when I have some spare time.

**Comment by Espesen** [comment]
7e7072f5 fixes the problem but quite awkwardly because you still have to keep track of how many event listeners you attach to the returned RuuviTag objects.
