### ISSUE TITLE
Data format 5 protocol

### ISSUE THREAD

**Issue by balda** [pakastin/node-ruuvitag#9]
Data format 5 protocol specification is now in master:

https://github.com/ruuvi/ruuvi-sensor-protocols#data-format-5-protocol-specification

Have you planned to handle it?

**Comment by Whoweez** [comment]
Yeah, Data format 5 would really be helpful!
Thanks :)

**Comment by ojousima** [comment]
The format 5 is supported in io53 fork: https://github.com/io53/node-ruuvitag

**Comment by balda** [comment]
Maybe @io53 can make a PR?

**Comment by akx** [comment]
Closed via b33fc3aa3937cc2a58fcb8c36dd6e3fbabffa0bb.
